/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  plugins: [require('@tailwindcss/typography')],
  theme: {
    extend: {
      colors: {
        'primary-container': '#2563eb',
        'on-primary': '#ffffff',
        primary: '#004ac6',
        'error-container': '#ffdad6',
        'tertiary-fixed-dim': '#ffb596',
        'on-tertiary': '#ffffff',
        'surface-dim': '#dadad8',
        'on-primary-fixed-variant': '#003ea8',
        'surface-container-highest': '#e1e1df',
        surface: '#f9f9f7',
        'on-surface': '#1a1a1a',
        background: '#f9f9f7',
        tertiary: '#943700',
        'surface-bright': '#f9f9f7',
        'on-secondary': '#ffffff',
        'inverse-primary': '#b4c5ff',
        'secondary-fixed-dim': '#ffb95f',
        'on-primary-fixed': '#00174b',
        'primary-fixed': '#dbe1ff',
        error: '#ba1a1a',
        'on-tertiary-container': '#ffede6',
        'inverse-on-surface': '#f0f0fb',
        'secondary-container': '#fea619',
        'tertiary-fixed': '#ffdbcd',
        'surface-container': '#ecece9',
        'surface-container-lowest': '#ffffff',
        'on-surface-variant': '#4a4a48',
        'primary-fixed-dim': '#b4c5ff',
        'on-background': '#1a1a1a',
        'on-tertiary-fixed-variant': '#7d2d00',
        'surface-tint': '#0053db',
        outline: '#767674',
        'on-error-container': '#93000a',
        'on-tertiary-fixed': '#360f00',
        secondary: '#855300',
        'surface-container-low': '#f4f4f2',
        'inverse-surface': '#2e2e2c',
        'on-secondary-fixed': '#2a1700',
        'on-error': '#ffffff',
        'surface-container-high': '#e7e7e4',
        'secondary-fixed': '#ffddb8',
        'on-secondary-fixed-variant': '#653e00',
        'on-secondary-container': '#684000',
        'tertiary-container': '#bc4800',
        'on-primary-container': '#eeefff',
        'outline-variant': '#c6c6c4',
        'surface-variant': '#e1e1df',
        'on-secondary-fixed-variant': '#653e00',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '16px',
        'margin-desktop': '48px',
        gutter: '24px',
        'section-gap-desktop': '128px',
        'section-gap-mobile': '64px',
        'container-max-width': '1280px',
        base: '8px',
      },
      maxWidth: {
        'container-max-width': '1280px',
      },
      fontFamily: {
        sans: ["'Noto Sans'", 'system-ui', 'sans-serif'],
        serif: ["'Noto Serif'", 'Georgia', 'serif'],
        'body-md': ["'Noto Sans'", 'system-ui', 'sans-serif'],
        'body-sm': ["'Noto Sans'", 'system-ui', 'sans-serif'],
        'body-lg': ["'Noto Sans'", 'system-ui', 'sans-serif'],
        'label-md': ["'Noto Sans'", 'system-ui', 'sans-serif'],
        'label-lg': ["'Noto Sans'", 'system-ui', 'sans-serif'],
        'headline-sm': ["'Noto Serif'", 'Georgia', 'serif'],
        'headline-md': ["'Noto Serif'", 'Georgia', 'serif'],
        'headline-lg': ["'Noto Serif'", 'Georgia', 'serif'],
        'headline-lg-mobile': ["'Noto Serif'", 'Georgia', 'serif'],
        'display-lg': ["'Noto Serif'", 'Georgia', 'serif'],
        'display-lg-mobile': ["'Noto Serif'", 'Georgia', 'serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-sm': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '1.2', fontWeight: '500' }],
        'headline-lg': ['48px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-lg-mobile': ['40px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
